package net.sf.persism.dao;

import net.sf.persism.annotations.NotColumn;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * Created with IntelliJ IDEA.
 * User: danhoward
 * Date: 12-05-15
 * Time: 4:43 PM
 */
public class Invoice {

    // todo Constructor String customerId, float price, int quantity, double discount, BigDecimal actualPrice, boolean paid
    private Integer invoiceId;
    private String customerId;
    private float price;
    private BigDecimal actualPrice;
    private int quantity;
    private double discount;

    @NotColumn
    private String junk1;

    private LocalDateTime created;

    @NotColumn
    private BigDecimal total;
    private boolean paid;

    // Used as a primitive to test for warning about using primitives on columns with defaults
    private int status;

    public String getCustomerId() {
        return customerId;
    }

    public void setCustomerId(String customerId) {
        this.customerId = customerId;
    }

    public Integer getInvoiceId() {
        return invoiceId;
    }

    public void setInvoiceId(Integer invoiceId) {
        this.invoiceId = invoiceId;
    }

    public float getPrice() {
        return price;
    }

    public void setPrice(float price) {
        this.price = price;
    }

    public int getQuantity() {
        return quantity;
    }

    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    public BigDecimal getTotal() {
        return total;
    }

    public void setTotal(BigDecimal total) {
        this.total = total;
    }

    public double getDiscount() {
        return discount;
    }

    public boolean isPaid() {
        return paid;
    }

    public void setPaid(boolean paid) {
        this.paid = paid;
    }

    public void setDiscount(double discount) {
        this.discount = discount;
    }

    // calculated property
    public String getJunk1() {
        return junk1 + " " + created;
    }


    // Read-only - generated by DB - NO Setter
    public LocalDateTime getCreated() {
        return created;
    }

    public int getStatus() {
        return status;
    }

    public void setStatus(int status) {
        this.status = status;
    }

    public BigDecimal getActualPrice() {
        return actualPrice;
    }

    public void setActualPrice(BigDecimal actualPrice) {
        this.actualPrice = actualPrice;
    }

    @Override
    public String toString() {
        return "Invoice{" +
                "invoiceId=" + invoiceId +
                ", customerId='" + customerId + '\'' +
                ", price=" + price +
                ", quantity=" + quantity +
                ", discount=" + discount +
                ", junk1='" + junk1 + '\'' +
                ", created=" + created +
                ", total=" + total +
                ", paid=" + paid +
                ", status=" + status +
                '}';
    }
}
