-- H2
CREATE TABLE Orders (
    ID IDENTITY PRIMARY KEY,
    NAME VARCHAR(30) NULL,
    PAID BIT NULL,
    EXTRA_COLUMN_NOT_MAPPED VARCHAR(30) NULL,
    Customer_ID VARCHAR(10) NULL,
    Created DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
)

-- SQLite
CREATE TABLE Orders (
    ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
    NAME VARCHAR(30) NULL,
    PAID BIT NULL,
    EXTRA_COLUMN_NOT_MAPPED VARCHAR(30) NULL,
    Customer_ID VARCHAR(10) NULL,
    CREATED DATETIME
)
